In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9])
x = x.reshape(1,2,3,3)
print(x)
print(np.sum(x, axis=(0,2,3)))

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]]
[45 45]


In [3]:
field_height=3
field_width=3
padding=1
stride=1

In [4]:
p = padding
x_padded = np.pad(x, ((0, 0), (0, 0), (p, p), (p, p)), mode='constant')
print(x_padded)

[[[[0 0 0 0 0]
   [0 1 2 3 0]
   [0 4 5 6 0]
   [0 7 8 9 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 1 2 3 0]
   [0 4 5 6 0]
   [0 7 8 9 0]
   [0 0 0 0 0]]]]


In [5]:
N, C, H, W = x.shape
assert (H + 2 * padding - field_height) % stride == 0
assert (W + 2 * padding - field_height) % stride == 0

In [6]:
out_height = (H + 2 * padding - field_height) / stride + 1
out_width = (W + 2 * padding - field_width) / stride + 1
print(out_height)
print(out_width)

3.0
3.0


In [7]:
i0 = np.arange(field_height,dtype='int32')
print(i0)

[0 1 2]


In [8]:
i0 = np.repeat(i0, field_width)
print(i0)

[0 0 0 1 1 1 2 2 2]


In [9]:
i0 = np.tile(i0, C)
print(i0)
print(i0.reshape(-1, 1))

[0 0 0 1 1 1 2 2 2 0 0 0 1 1 1 2 2 2]
[[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]]


In [10]:
i1 = stride * np.repeat(np.arange(out_height,dtype='int32'), out_width)
print(i1)
print(i1.reshape(1, -1))

[0 0 0 1 1 1 2 2 2]
[[0 0 0 1 1 1 2 2 2]]


In [11]:
j0 = np.tile(np.arange(field_width), field_height * C)
print(j0)

[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]


In [12]:
j1 = stride * np.tile(np.arange(out_width,dtype='int32'), int(out_height))
print(j1)

[0 1 2 0 1 2 0 1 2]


In [13]:
i = i0.reshape(-1, 1) + i1.reshape(1, -1)
print(i)

[[0 0 0 1 1 1 2 2 2]
 [0 0 0 1 1 1 2 2 2]
 [0 0 0 1 1 1 2 2 2]
 [1 1 1 2 2 2 3 3 3]
 [1 1 1 2 2 2 3 3 3]
 [1 1 1 2 2 2 3 3 3]
 [2 2 2 3 3 3 4 4 4]
 [2 2 2 3 3 3 4 4 4]
 [2 2 2 3 3 3 4 4 4]
 [0 0 0 1 1 1 2 2 2]
 [0 0 0 1 1 1 2 2 2]
 [0 0 0 1 1 1 2 2 2]
 [1 1 1 2 2 2 3 3 3]
 [1 1 1 2 2 2 3 3 3]
 [1 1 1 2 2 2 3 3 3]
 [2 2 2 3 3 3 4 4 4]
 [2 2 2 3 3 3 4 4 4]
 [2 2 2 3 3 3 4 4 4]]


In [14]:
j = j0.reshape(-1, 1) + j1.reshape(1, -1)
print(j)

[[0 1 2 0 1 2 0 1 2]
 [1 2 3 1 2 3 1 2 3]
 [2 3 4 2 3 4 2 3 4]
 [0 1 2 0 1 2 0 1 2]
 [1 2 3 1 2 3 1 2 3]
 [2 3 4 2 3 4 2 3 4]
 [0 1 2 0 1 2 0 1 2]
 [1 2 3 1 2 3 1 2 3]
 [2 3 4 2 3 4 2 3 4]
 [0 1 2 0 1 2 0 1 2]
 [1 2 3 1 2 3 1 2 3]
 [2 3 4 2 3 4 2 3 4]
 [0 1 2 0 1 2 0 1 2]
 [1 2 3 1 2 3 1 2 3]
 [2 3 4 2 3 4 2 3 4]
 [0 1 2 0 1 2 0 1 2]
 [1 2 3 1 2 3 1 2 3]
 [2 3 4 2 3 4 2 3 4]]


In [15]:
k = np.repeat(np.arange(C,dtype='int32'), field_height * field_width).reshape(-1, 1)
print(k)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [16]:
cols = x_padded[:, k, i, j]
print(cols)

[[[0 0 0 0 1 2 0 4 5]
  [0 0 0 1 2 3 4 5 6]
  [0 0 0 2 3 0 5 6 0]
  [0 1 2 0 4 5 0 7 8]
  [1 2 3 4 5 6 7 8 9]
  [2 3 0 5 6 0 8 9 0]
  [0 4 5 0 7 8 0 0 0]
  [4 5 6 7 8 9 0 0 0]
  [5 6 0 8 9 0 0 0 0]
  [0 0 0 0 1 2 0 4 5]
  [0 0 0 1 2 3 4 5 6]
  [0 0 0 2 3 0 5 6 0]
  [0 1 2 0 4 5 0 7 8]
  [1 2 3 4 5 6 7 8 9]
  [2 3 0 5 6 0 8 9 0]
  [0 4 5 0 7 8 0 0 0]
  [4 5 6 7 8 9 0 0 0]
  [5 6 0 8 9 0 0 0 0]]]


In [17]:
C = x.shape[1]
#cols = cols.transpose(1, 2, 0).reshape(-1, field_height, field_width)
cols = cols.transpose(1, 2, 0).reshape(field_height * field_width * C, -1)
print(cols)

[[0 0 0 0 1 2 0 4 5]
 [0 0 0 1 2 3 4 5 6]
 [0 0 0 2 3 0 5 6 0]
 [0 1 2 0 4 5 0 7 8]
 [1 2 3 4 5 6 7 8 9]
 [2 3 0 5 6 0 8 9 0]
 [0 4 5 0 7 8 0 0 0]
 [4 5 6 7 8 9 0 0 0]
 [5 6 0 8 9 0 0 0 0]
 [0 0 0 0 1 2 0 4 5]
 [0 0 0 1 2 3 4 5 6]
 [0 0 0 2 3 0 5 6 0]
 [0 1 2 0 4 5 0 7 8]
 [1 2 3 4 5 6 7 8 9]
 [2 3 0 5 6 0 8 9 0]
 [0 4 5 0 7 8 0 0 0]
 [4 5 6 7 8 9 0 0 0]
 [5 6 0 8 9 0 0 0 0]]


In [19]:
self.d_X, self.h_X, self.w_X = X_dim

self.n_filter, self.h_filter, self.w_filter = n_filter, h_filter, w_filter
self.stride, self.padding = stride, padding

self.W = np.random.randn(
    n_filter, self.d_X, h_filter, w_filter) / np.sqrt(n_filter / 2.)
self.b = np.bzeros((self.n_filter, 1))
self.params = [self.W, self.b]

self.h_out = (self.h_X - h_filter + 2 * padding) / stride + 1
self.w_out = (self.w_X - w_filter + 2 * padding) / stride + 1

if not self.h_out.is_integer() or not self.w_out.is_integer():
    raise Exception("Invalid dimensions!")

self.h_out, self.w_out = int(self.h_out), int(self.w_out)
self.out_dim = (self.n_filter, self.h_out, self.w_out)

NameError: name 'X_dim' is not defined