In [30]:
import numpy as np

In [31]:
x = np.array([1,2,3,4,5,6,7,8,9,9,8,7,6,5,4,3,2,1,1,2,3,4,5,6,7,8,9,9,8,7,6,5,4,3,2,1])
x = x.reshape(1,2,3,2,3)
print(x)

[[[[[1 2 3]
    [4 5 6]]

   [[7 8 9]
    [9 8 7]]

   [[6 5 4]
    [3 2 1]]]


  [[[1 2 3]
    [4 5 6]]

   [[7 8 9]
    [9 8 7]]

   [[6 5 4]
    [3 2 1]]]]]


In [32]:
field_height=2
field_width=2
field_depth=2
padding=1
stride=1

In [33]:
p = padding
x_padded = np.pad(x, ((0, 0), (0, 0), (p, p), (p, p), (p, p)), mode='constant')

In [39]:
N, C, D, H, W = x.shape
assert (H + 2 * padding - field_height) % stride == 0
assert (W + 2 * padding - field_width) % stride == 0
assert (D + 2 * padding - field_depth) % stride == 0

In [40]:
out_height = (H + 2 * padding - field_height) / stride + 1
out_width = (W + 2 * padding - field_width) / stride + 1
out_depth = (D + 2 * padding - field_depth) / stride + 1
print(out_height)
print(out_width)
print(out_depth)

3.0
4.0
4.0


In [41]:
i0 = np.arange(field_depth,dtype='int32')
print(i0)

[0 1]


In [42]:
i0 = np.repeat(i0, field_width * field_depth)
print(i0)

[0 0 0 0 1 1 1 1]


In [43]:
i0 = np.tile(i0, C)
print(i0)

[0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]


In [19]:
i1 = stride * np.repeat(np.arange(out_height,dtype='int32'), out_width * out_depth)
print(i1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2]


In [20]:
i2 = stride * np.repeat(np.arange(out_height, dtype='int32'), out_width)
print(i2)

[0 0 0 0 1 1 1 1 2 2 2 2]


In [44]:
j0 = np.tile(np.arange(field_width), field_height * field_depth * C)
print(j0)

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


In [45]:
j1 = stride * np.tile(np.arange(out_width,dtype='int32'), int(out_height * out_depth))
print(j1)

[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0
 1 2 3 0 1 2 3 0 1 2 3]


In [46]:
j2 = stride * np.tile(np.arange(out_width,dtype='int32'), int(out_height * out_depth))
print(j2)

[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0
 1 2 3 0 1 2 3 0 1 2 3]


In [47]:
d1 = stride * np.tile(np.arange(out_depth, dtype='int32'), int(out_height * out_width))
print(d1)

[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0
 1 2 3 0 1 2 3 0 1 2 3]


In [48]:
d2 = stride * np.tile(np.arange(out_depth, dtype='int32'), int(out_height * out_width))
print(d2)

[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0
 1 2 3 0 1 2 3 0 1 2 3]


In [51]:
i = i0.reshape(-1, 1, 1) + i1.reshape(1, -1, 1)
print(i)

[[[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]
  [2]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1

In [52]:
j = j0.reshape(-1, 1, 1) + j1.reshape(1, -1, 1)
print(j)

[[[0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]]

 [[1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]]

 [[0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]
  [0]
  [1]
  [2]
  [3]]

 [[1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2]
  [3]
  [4]
  [1]
  [2

In [ ]:
d = j0.reshape(-1, 1, 1) + j1.reshape(1, -1, 1)
print(d)

In [28]:
k = np.repeat(np.arange(C,dtype='int32'), field_height * field_width * field_depth).reshape(-1, 1, 1)
print(k)

[[[0]]

 [[0]]

 [[0]]

 [[0]]

 [[0]]

 [[0]]

 [[0]]

 [[0]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]]


In [29]:
cols = x_padded[:, k, i, j]
print(cols)

IndexError: index 5 is out of bounds for axis 2 with size 5

In [ ]:
C = x.shape[1]
cols = cols.transpose(1, 2, 0).reshape(field_height * field_width * C, -1)
print(cols)