In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9])
x = x.reshape(2,3,3)
print(x)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [3]:
field_height=3
padding=1
stride=1

In [4]:
p = padding
x_padded = np.pad(x, ((0,0), (p,p), (p,p)), mode='constant')
print(x_padded)

[[[0 0 0 0 0]
  [0 1 2 3 0]
  [0 4 5 6 0]
  [0 7 8 9 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 1 2 3 0]
  [0 4 5 6 0]
  [0 7 8 9 0]
  [0 0 0 0 0]]]


In [5]:
N, C, H = x.shape
assert (H + 2 * padding - field_height) % stride == 0


In [6]:
out_height = (H + 2 * padding - field_height) / stride + 1
print(out_height)


3.0


In [7]:
i0 = np.arange(field_height,dtype='int32')
print(i0)

[0 1 2]


In [8]:
i0 = np.tile(i0, C)
print(i0)

[0 1 2 0 1 2 0 1 2]


In [9]:
i1 = stride * np.arange(out_height ,dtype='int32')
print(i1)

[0 1 2]


In [10]:
i = i0.reshape(-1, 1) + i1.reshape(1, -1)
print(i)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [0 1 2]
 [1 2 3]
 [2 3 4]
 [0 1 2]
 [1 2 3]
 [2 3 4]]


In [11]:
k = np.repeat(np.arange(C,dtype='int32'), field_height).reshape(-1, 1)
print(k)

[[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]]


In [26]:
cols = x_padded[:, k, i]
print(cols)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 1 2]
  [1 2 3]
  [2 3 0]
  [0 4 5]
  [4 5 6]
  [5 6 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 1 2]
  [1 2 3]
  [2 3 0]
  [0 4 5]
  [4 5 6]
  [5 6 0]]]


In [27]:
C = x.shape[1]
cols = cols.reshape(-1, 1, field_height)
print(cols)

[[[0 0 0]]

 [[0 0 0]]

 [[0 0 0]]

 [[0 1 2]]

 [[1 2 3]]

 [[2 3 0]]

 [[0 4 5]]

 [[4 5 6]]

 [[5 6 0]]

 [[0 0 0]]

 [[0 0 0]]

 [[0 0 0]]

 [[0 1 2]]

 [[1 2 3]]

 [[2 3 0]]

 [[0 4 5]]

 [[4 5 6]]

 [[5 6 0]]]
