In [3]:
import keras
import numpy as np
from keras import backend as K


Using TensorFlow backend.


ModuleNotFoundError: No module named 'tensorflow'

In [62]:
y_pred = np.array([9,8,7,6,5,4,3,2,1]);
y_pred = y_pred.reshape(3, -1);
y_pred = K.variable(y_pred)

y_true = np.array([-1,2,3,-4,5,6,7,-8,9]);
y_true = y_true.reshape(3, -1);
y_true = K.variable(y_true)

In [44]:
loss = keras.losses.cosine_proximity(y_true, y_pred)
print(K.eval(loss))

grad = K.gradients(loss, y_pred)
print(K.eval(grad[0]))

[-0.53727067 -0.32467535 -0.26863533]
[[ 0.04411317 -0.01622099 -0.03817866]
 [ 0.07724743 -0.04385225 -0.06105583]
 [-0.07675295  0.19188239 -0.1535059 ]]


In [1]:
x = np.array([-1,2,3,-4,5,6,7,-8,9]);
x = x.reshape(3, -1);
print(np.sum(x))

NameError: name 'np' is not defined