In [57]:
import keras
import numpy as np
from keras import backend as K
import tensorflow as tf

In [72]:
x = np.array([-1,2,3,-4,5,6,7,-8,9]);
x = x.reshape(3, -1);
x = K.variable(x)
y = keras.activations.elu(x)
print(K.eval(y))

der = K.gradients(y, x)
print(K.eval(der[0]))

[[-0.63212055  2.          3.        ]
 [-0.9816844   5.          6.        ]
 [ 7.         -0.99966455  9.        ]]
[[3.6787945e-01 1.0000000e+00 1.0000000e+00]
 [1.8315613e-02 1.0000000e+00 1.0000000e+00]
 [1.0000000e+00 3.3545494e-04 1.0000000e+00]]


In [54]:
X = np.array([1,2,3,4,5,6,7,8,9]);
X = X.reshape(3, -1);
W = np.ones((3, 6))
b = np.ones((1, 6))
def forward(X):
    out = X @ W + b
    return out

def backward(dout):
    dW = X.T @ dout
    db = np.sum(dout, axis=0)
    dX = dout @ W.T
    return dX, dW, db

In [55]:
Y = forward(X)
print(Y)

[[ 7.  7.  7.  7.  7.  7.]
 [16. 16. 16. 16. 16. 16.]
 [25. 25. 25. 25. 25. 25.]]


In [56]:
dX, dW, db = backward(Y)
print(dX)
print(dW)
print(db)

[[ 42.  42.  42.]
 [ 96.  96.  96.]
 [150. 150. 150.]]
[[246. 246. 246. 246. 246. 246.]
 [294. 294. 294. 294. 294. 294.]
 [342. 342. 342. 342. 342. 342.]]
[48. 48. 48. 48. 48. 48.]
