In [1]:
import keras
import numpy as np
from keras import backend as K

Using TensorFlow backend.


In [23]:
x = np.array([-1, 2, 3, -4, 5, 6, 7, -8, 9]);
x = x.reshape(-1, 3);
x = K.variable(x)

grad = np.array([1, -1, -2, 2, -3, -4, 5, 4, -5]);
grad = grad.reshape(-1, 3);
grad = K.variable(grad)

l = keras.layers.Dense(units=3, activation=None, use_bias=True, kernel_initializer='ones', bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, bias_constraint=None)
l.build((3,3))
y = l.call(x)
print(K.eval(y))

grads = grad * K.gradients(y, keras.initializers.ones((1, 3)))
print(K.eval(grads[0]))

[[4. 4. 4.]
 [7. 7. 7.]
 [8. 8. 8.]]


TypeError: object() takes no parameters