In [57]:
import keras
import numpy as np
from keras import backend as K
import tensorflow as tf

In [80]:
x = np.array([-1,2,3,-4,5,6,7,-8,9]);
x = x.reshape(3, -1);
x = K.variable(x)
y = keras.activations.selu(x)
print(K.eval(y))

der = y * K.gradients(y, x)
print(K.eval(der[0]))

[[-1.1113307  2.101402   3.152103 ]
 [-1.7258987  5.253505   6.304206 ]
 [ 7.354907  -1.7575095  9.456309 ]]
[[-7.1877384e-01  2.2079453e+00  3.3119178e+00]
 [-5.5575091e-02  5.5198631e+00  6.6238356e+00]
 [ 7.7278085e+00 -1.0365143e-03  9.9357538e+00]]


In [54]:
X = np.array([1,2,3,4,5,6,7,8,9]);
X = X.reshape(3, -1);
W = np.ones((3, 6))
b = np.ones((1, 6))
def forward(X):
    out = X @ W + b
    return out

def backward(dout):
    dW = X.T @ dout
    db = np.sum(dout, axis=0)
    dX = dout @ W.T
    return dX, dW, db

In [55]:
Y = forward(X)
print(Y)

[[ 7.  7.  7.  7.  7.  7.]
 [16. 16. 16. 16. 16. 16.]
 [25. 25. 25. 25. 25. 25.]]


In [56]:
dX, dW, db = backward(Y)
print(dX)
print(dW)
print(db)

[[ 42.  42.  42.]
 [ 96.  96.  96.]
 [150. 150. 150.]]
[[246. 246. 246. 246. 246. 246.]
 [294. 294. 294. 294. 294. 294.]
 [342. 342. 342. 342. 342. 342.]]
[48. 48. 48. 48. 48. 48.]
