In [4]:
import numpy as np
import tensorflow as tf

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,9,8,7,6,5,4,3,2,1])
x = x.reshape(1,2,3,3)
print(x)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]]]


In [10]:
print(np.max(x, axis=(2,3)).shape)

(1, 2)
