In [2]:
import numpy as np

In [39]:
x = np.array([1,2,3,4,5,6,7,8,9])
x = x.reshape(3,1,3)
print(x)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [40]:
a = np.arange(5, 10, 2)
print(a)

[5 7 9]


In [45]:
r = np.repeat(x, 2, 1)
print(r)

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]]]


In [60]:
print(x[:,1,1,1)

SyntaxError: invalid syntax (<ipython-input-60-49387dc692a8>, line 1)

In [22]:
a = np.array([1,2,3,4,5,6])
a = a.reshape(6, 1)

b = np.array([1,2,3,4,5,6,7,8])
b = b.reshape(1, 8)

#print(a)
#print(b)

c = a + b
print(c)

[[ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]]
