In [6]:
import numpy as np
import tensorflow as tf
import keras
import keras.backend as K

Using TensorFlow backend.


In [2]:
x = np.array([1,2,3,4,5,6,7,8,9])
diag = np.diag(x)
print(diag)

[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]


In [17]:
x = np.array([1,2,3,4,5,6,7,8,9,9,8,7,6,5,4,3,2,1])
x = x.reshape(3,6)
x = K.variable(x)

y = K.softmax(x)
print(K.eval(y))

dy = K.variable(np.array([1, -1, -2, 2, -3, -4, 5, 4, -5, 1, -1, -2, 2, -3, -4, 5, 4, -5]).reshape(3, -1))
grad = dy * K.gradients(y, x)

print(K.eval(grad[0]))


[[0.00426978 0.01160646 0.03154963 0.08576079 0.233122   0.6336913 ]
 [0.04501529 0.12236424 0.33262047 0.33262047 0.12236424 0.04501529]
 [0.6336913  0.233122   0.08576079 0.03154963 0.01160646 0.00426978]]
[[ 0.0000000e+00 -0.0000000e+00 -0.0000000e+00  0.0000000e+00
  -0.0000000e+00 -0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00 -0.0000000e+00  0.0000000e+00
  -0.0000000e+00 -0.0000000e+00]
 [ 7.5541891e-08 -4.1685464e-08 -2.0446967e-08  9.4025232e-09
   2.7671960e-09 -1.2724931e-09]]


In [52]:
def softmax_grad(s):
    # input s is softmax value of the original input x. Its shape is (1,n) 
    # i.e.  s = np.array([0.3,0.7]),  x = np.array([0,1])
    s = K.eval(K.softmax(K.variable(s)))
    s = s.reshape(-1,1)
    print(np.diagflat(s).shape)
    return np.diagflat(s) - np.dot(s, s.T)

In [53]:
x = np.array([1,2,3,4,5,6,7,8,9,9,8,7,6,5,4,3,2,1])
x = x.reshape(3,6)
dy1 = np.array([1, -1, -2, 2, -3, -4, 5, 4, -5, 1, -1, -2, 2, -3, -4, 5, 4, -5])
dy1 = dy1.reshape(3, -1)
grad1 = dy1 * softmax_grad(x).sum(0).reshape(3, -1)
print(grad1)

(18, 18)
[[-0.00853956  0.02321292  0.12619853 -0.34304315  1.39873195  5.06953001]
 [-0.45015283 -0.9789139   3.32620442 -0.66524088  0.24472848  0.18006112]
 [-2.53476501  1.39873186  0.68608636 -0.31549633 -0.0928517   0.04269778]]
