In [2]:

import numpy as np

In [39]:
x = np.array([1,2,3,4,5,6,7,8,9])
x = x.reshape(3,1,3)
print(x)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [40]:
a = np.arange(5, 10, 2)
print(a)

[5 7 9]


In [45]:
r = np.repeat(x, 2, 1)
print(r)

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]]]


In [52]:
print(x[:[[1]]])

TypeError: slice indices must be integers or None or have an __index__ method