In [4]:
import keras
import numpy as np
from keras import backend as K


In [36]:
x = np.array([-1,2,3,-4,5,6,7,-8,9]);
x = x.reshape(3, -1);
x = K.variable(x)

In [48]:
c = keras.initializers.glorot_uniform(seed=7)
w = c.__call__(shape=(3,3))
print(K.eval(w))

[[-0.03211808  0.01240611 -0.48971248]
 [-0.75051546  0.8660202   0.32921863]
 [-0.5415511   0.6884544   0.53820705]]
